name: Github CI Action

on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: ["*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr-lint:
    name: Run PR Lint
    runs-on: ubuntu-latest
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  typecheck:
    name: Typecheck with mypy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      # - uses: chartboost/ruff-action@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run mypy typechecker
        run: pipenv run typecheck

  build_macos:
    name: Build for macOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install create-dmg
        run: brew install create-dmg
      - name: Install dependencies
        run: pipenv install --dev
      - name: Build for macOS
        run: pipenv run build_osx
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: MacOS Build
          path: dist/Carpet.dmg
          retention-days: 5
